### ISSUE TITLE
Closed Cross-platform support

### ISSUE THREAD

**Issue by Jmallins** [kungfujam/habitica_hacks#1]
It would be good if dl_party_info.sh supported Windows© (3.1-10)

**Comment by JamesOwers** [comment]
Great suggestion John; I'll let you get on with it :wink: .

**Comment by kungfujam** [comment]
Off you go!

**Comment by JamesOwers** [comment]
For those interested in tracking progress with supporting Windows© (3.1-8), check out John's fork. It's rad.
